binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode:
        input: true
        pullup: true
      inverted: true
    id: top_btn
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms

    on_click:
      # Short press → cycle brightness levels
      - min_length: 1ms
        max_length: 490ms
        then:
          - lambda: |-
              // Cycle through brightness levels: 33% → 15% → OFF → 100% → 33%
              auto current = id(display_brightness).state;
              if (current == 33) {
                id(display_brightness).publish_state(15);    // 33% → 15%  ← CHANGED 5 TO 15
              } else if (current == 15) {                    // ← CHANGED 5 TO 15
                id(display_brightness).publish_state(0);     // 15% → OFF
              } else if (current == 0) {
                id(display_brightness).publish_state(100);   // OFF → 100%
              } else {
                id(display_brightness).publish_state(33);    // 100% or unknown → 33%
              }

      # Long press → switch page
      - min_length: 500ms
        max_length: 2000ms
        then:
          - lambda: |-
              id(page_number) = (id(page_number) + 1) % id(page_count);

      # Very long press → toggle Wi-Fi
      - min_length: 2200ms
        max_length: 5000ms
        then: 
          - if:
              condition: wifi.enabled 
              then:
                - wifi.disable:
                - lambda: |-
                    id(wifi_status) = -1;
              else:
                - wifi.enable:
                - lambda: |-
                    id(wifi_status) = 1;
                    id(page_number) = 0;
          - delay: 3s
          - lambda: |-
              id(wifi_status) = 0;

      # Ultra long press → save SGP30 baseline (manual)
      - min_length: 5100ms
        max_length: 7500ms
        then:
          - lambda: |-
              float co2 = id(eco2_sgp30).state;
              float voc = id(tvoc_sgp30).state;

              if (co2 >= 0 && co2 <= 2000 && voc >= 0 && voc <= 400) {
                id(sgp30_baseline_eco2) = co2;
                id(sgp30_baseline_tvoc) = voc;
                id(baseline_status) = 1;
              } else {
                id(baseline_status) = -1;
              }

          - delay: 3s
          - lambda: |-
              id(baseline_status) = 0;

sensor:
  - platform: template
    id: temperature
    name: "Temperature"
    device_class: "temperature"
    state_class: "measurement"
    update_interval: 10s
    lambda: |-
      float temps[6] = { 
        id(temp_sht40).state, 
        id(temp_aht20).state, 
        id(temp_scd40).state, 
        id(temp_aht20_ens).state, 
        id(temp_bmp280).state,
      };

      for (int i = 0; i < 5; i++) {
        if (!isnan(temps[i])) { 
          return temps[i]; 
        }
      }
      return 0.0;

  - platform: template
    id: humidity
    name: "Humidity"
    device_class: "humidity"
    state_class: "measurement"
    update_interval: 10s
    lambda: |-
      float hums[4] = { 
        id(hum_sht40).state, 
        id(hum_aht20).state, 
        id(hum_scd40).state, 
        id(hum_aht20_ens).state, 
      };

      for (int i = 0; i < 4; i++) {
        if (!isnan(hums[i])) { 
          return hums[i]; 
        }
      }

      return 0.0;

  - platform: template
    name: "ZE08 CH2O"
    unit_of_measurement: ppb
    state_class: measurement
    device_class: volatile_organic_compounds
    id: ch2o_ze08
    update_interval: 5s
    filters: 
      - filter_out: 2000.0
      - exponential_moving_average: 
          send_every: 1
          alpha: 0.5

  - platform: aht10
    #address: 0x38
    i2c_id: i2c_main
    variant: AHT20
    temperature:
      name: "AHT20 Temperature"
      id: temp_aht20
    humidity:
      name: "AHT20 Humidity"
      id: hum_aht20
    update_interval: 10s

  - platform: bmp280_i2c
    address: 0x77
    i2c_id: i2c_main
    temperature:
      name: "BMP280 Temperature"
      id: temp_bmp280
      oversampling: 16x
    pressure:
      name: "BMP280 Pressure"
      id: pres_bmp280
    update_interval: 10s

  - platform: sht4x
    #addr 0x44
    i2c_id: i2c_main
    temperature:
      name: "SHT40 Temperature"
      id: temp_sht40
    humidity:
      name: "SHT40 Relative Humidity"
      id: hum_sht40
    update_interval: 10s

  - platform: scd4x
    #address: 0x62
    i2c_id: i2c_main
    co2:
      name: "SCD40 CO2"
      id: co2_scd40
    temperature:
      name: "SCD40 Temperature"
      id: temp_scd40
    humidity:
      name: "SCD40 Humidity"
      id: hum_scd40
    update_interval: 30s

  - platform: ens160_i2c
    address: 0x53
    i2c_id: i2c_2
    eco2:
      name: "ENS160 eCO2"
      id: eco2_ens160
    tvoc:
      name: "ENS160 TVOC"
      id: tvoc_ens160
      filters: 
        - exponential_moving_average: 
            send_every: 1
            alpha: 0.5
    aqi:
      name: "ENS160 Air Quality Index"
      id: aqi_ens160
    update_interval: 10s
    compensation:
      temperature: temp_aht20_ens
      humidity: hum_aht20_ens

  - platform: aht10
    #address: 0x38
    i2c_id: i2c_2
    variant: AHT20
    temperature:
      name: "AHT20/ENS160 Temperature"
      id: temp_aht20_ens
      disabled_by_default: True
    humidity:
      name: "AHT20/ENS160 Humidity"
      id: hum_aht20_ens
      disabled_by_default: True
    update_interval: 10s

  - platform: sgp30
    id: sgp30_component
    i2c_id: i2c_main
    address: 0x58
    eco2:
      name: "SGP30 eCO2"
      id: eco2_sgp30
      accuracy_decimals: 0
      filters: 
        - exponential_moving_average: 
            send_every: 1
            alpha: 0.2
    tvoc:
      name: "SGP30 TVOC"
      id: tvoc_sgp30
      accuracy_decimals: 1
      filters: 
        - exponential_moving_average: 
            send_every: 1
            alpha: 0.2
    store_baseline: yes
    update_interval: 5s
    compensation: 
      humidity_source: hum_aht20
      temperature_source: temp_aht20

  - platform: sgp4x
    i2c_id: i2c_main
    #address: 0x59
    voc:
      name: "SGP41 VOC Index"
      id: aqi_voc_sgp41
      icon: "mdi:air-filter"
      device_class: aqi
      state_class: measurement
      unit_of_measurement: "index points"
    nox:
      name: "SGP41 NOx Index"
      id: aqi_nox_sgp41
      icon: "mdi:air-filter"
      device_class: aqi
      state_class: measurement
      unit_of_measurement: "index points"
    compensation: 
      humidity_source: hum_aht20
      temperature_source: temp_aht20
    store_baseline: True
    update_interval: 10s

  - platform: pmsx003
    type: PMSX003 
    update_interval: 120s
    uart_id: uart_pms
    pm_1_0:
      name: "PMS Particulate Matter <1.0µm Concentration"
      id: pm1_pms
    pm_2_5:
      name: "PMS Particulate Matter <2.5µm Concentration"
      id: pm25_pms
    pm_10_0:
      name: "PMS Particulate Matter <10.0µm Concentration"
      id: pm10_pms

  - platform: template
    id: tvoc_sgp30_capped
    name: "SGP30 TVOC Capped"
    lambda: |-
      auto voc = id(tvoc_sgp30).state;
      if (isnan(voc)) return NAN;
      return (voc > 1000) ? 1000 : voc;
    update_interval: 5s